// <auto-generated />
namespace SignalRSelfHost.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class virtual_navigation_items : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(virtual_navigation_items));
        
        string IMigrationMetadata.Id
        {
            get { return "201404301454462_virtual_navigation_items"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
